// Generated by GSE. Edit at your own risk.

#if !defined(USER_IMAGE_RESOURCE_H)
#define USER_IMAGE_RESOURCE_H

#define USER_IMAGE_TABLE            \
ENTRY(IMG_SWITCH_BLUE_ON, "switch_blue_on.png", false)    \
ENTRY(IMG_SWITCH_BLUE_OFF, "switch_blue_off.png", false)    \
ENTRY(IMG_SWITCH_GREEN_OFF, "switch_green_off.png", false)    \
ENTRY(IMG_SWITCH_GREEN_ON, "switch_green_on.png", false)    \
ENTRY(LAST_GENERATED_IMAGE_ID, "", true)

#endif // USER_IMAGE_RESOURCE_H
