// Generated by GSE. Edit at your own risk.

#if !defined(USER_IMAGE_RESOURCE_H)
#define USER_IMAGE_RESOURCE_H

#define USER_IMAGE_TABLE            \
ENTRY(IMG_PROGRESSBG, "ProgressBG.png", false)    \
ENTRY(IMG_PROGRESSFG_HORI, "ProgressFG_Hori.png", false)    \
ENTRY(IMG_PROGRESSFG_VERT, "ProgressFG_Vert.png", false)    \
ENTRY(IMG_PB_FILL, "PB_Fill.png", false)    \
ENTRY(LAST_GENERATED_IMAGE_ID, "", true)

#endif // USER_IMAGE_RESOURCE_H
