// Generated by GSE. Edit at your own risk.

#if !defined(USER_IMAGE_RESOURCE_H)
#define USER_IMAGE_RESOURCE_H

#define USER_IMAGE_TABLE            \
ENTRY(IMG_ROUND_BUTTON_HOVER_BLUE, "round_button_hover_blue.png", false)    \
ENTRY(IMG_ROUND_BUTTON_STD_GRAY, "round_button_std_gray.png", false)    \
ENTRY(LAST_GENERATED_IMAGE_ID, "", true)

#endif // USER_IMAGE_RESOURCE_H
